[project]
name = "33langchain-rag-rerank"
version = "0.1.0"
description = "Rerank"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "winnie-playground-common",
    "langchain>=1.0.0",
    "langchain-openai>=1.0.0",
    "python-dotenv>=1.0.0",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["c33"]

[tool.uv.sources]
winnie-playground-common = { path = "../common", editable = true }
